more consistently formatted output

diff --git a/bin/bd-install b/bin/bd-install
--- a/bin/bd-install
+++ b/bin/bd-install
@@ -59,12 +59,12 @@ BD_INSTALL_REQUIRED+=("mkdir")
 for BD_INSTALL_REQUIRE in ${BD_INSTALL_REQUIRED[@]}; do
     # ensure gnu dependency
     if ! type -P ${BD_INSTALL_REQUIRE} &> /dev/null; then
-        echo "# [ERROR] ... ${BD_INSTALL_REQUIRE} executable not found; install gnu ${BD_INSTALL_REQUIRE}" && exit 1
+        echo "# [ERROR] ... '${BD_INSTALL_REQUIRE}' executable not found; install gnu ${BD_INSTALL_REQUIRE}" && exit 1
     fi
 
     # ensure gnu dependency works
     if ! ${BD_INSTALL_REQUIRE} --version 2>&1 | grep -q ^${BD_INSTALL_REQUIRE}; then
-        echo "# [ERROR] ... ${BD_INSTALL_REQUIRE} executable not working as expected" && exit 1
+        echo "# [ERROR] ... '${BD_INSTALL_REQUIRE}' executable not working as expected" && exit 1
     fi
 done
 unset BD_INSTALL_REQUIRE unset BD_INSTALL_REQUIRED
@@ -81,6 +81,7 @@ echo
 [ ! -d "${BD_DIR}" ] && mkdir -p "${BD_DIR}"
 [ ! -d "${BD_DIR}" ] && echo "# [ERROR] ... '${BD_DIR}' directory not found" && echo && exit 1
 [ ! -w "${BD_DIR}" ] && echo "# [ERROR] ... '${BD_DIR}' directory not writable" && echo && exit 1
+
 echo "# [OK] ... '${BD_DIR}' directory found"
 echo
 
@@ -93,16 +94,16 @@ if [ "${BD_INSTALL_EXISTS}" == "1" ]; then
     [ $? -ne 0 ] && echo "# [ERROR] ... 'git pull ${BD_DIR}' failed" && cd "${BD_INSTALL_PWD}" && exit 1
     cd "${BD_INSTALL_PWD}"
     unset -v BD_INSTALL_PWD
-    echo "# [OK] ... updating from '${BD_GIT_URL}"
+    echo "# [OK] ... '${BD_GIT_URL}' pulled"
 else
     git clone ${BD_GIT_URL} ${BD_DIR} && echo
     [ $? -ne 0 ] && echo "# [ERROR] ... 'git clone ${BD_GIT_URL} ${BD_DIR}' failed" && exit 1
-    echo "# [OK] ... installed from '${BD_GIT_URL}'"
+    echo "# [OK] ... '${BD_GIT_URL}' installed"
 fi
 echo
 
-[ ! -r "${BD_DIR}/.bash_profile" ] && echo "# [ERROR] ... ${BD_DIR}/.bash_profile file not found readable" && exit 1
-[ ! -r "${BD_DIR}/.bashrc" ] && echo "# [ERROR] ... ${BD_DIR}/.bashrc file not found readable" && exit 1
+[ ! -r "${BD_DIR}/.bash_profile" ] && echo "# [ERROR] ... '${BD_DIR}/.bash_profile' file not found readable" && exit 1
+[ ! -r "${BD_DIR}/.bashrc" ] && echo "# [ERROR] ... '${BD_DIR}/.bashrc' file not found readable" && exit 1
 
 BD_INSTALL_TIMESTAMP="$(date +%y%m%d%H%M%S%z)" # posix
 
@@ -111,18 +112,18 @@ if [ "${BD_INSTALL_APPEND}" == "1" ]; then
     if [ -f ~/.bash_profile ]; then
         BD_INSTALL_APPEND_BASH_PROFILE="$(grep -E -e ' (.|source) (.*)/.bashrc( |$|")' ~/.bash_profile 2> /dev/null)"
         if [ ${#BD_INSTALL_APPEND_BASH_PROFILE} -gt 0 ]; then
-            echo "# [OK] ... ~/.bashrc is sourced via ~/.bash_profile"
+            echo "# [OK] ... '~/.bash_profile' sources '~/.bashrc'"
         else
             if [ -f ~/.bash_profile ]; then
                 cp ~/.bash_profile ~/.bash_profile.${BD_INSTALL_TIMESTAMP}
                 [ $? -ne 0 ] && echo "# [ERROR] ... 'cp ~/.bash_profile ~/.bash_profile.${BD_INSTALL_TIMESTAMP}' failed" && exit 1
-                echo "# [OK] ... backed up ~/.bash_profile to ~/.bash_profile.${BD_INSTALL_TIMESTAMP}"
+                echo "# [OK] ...'~/.bash_profile.${BD_INSTALL_TIMESTAMP}' backed up"
                 echo
             fi
             echo >> ~/.bash_profile
             echo '. ~/.bashrc' >> ~/.bash_profile
             [ $? -ne 0 ] && echo "# [ERROR] ... 'echo '. ~/.bashrc' >> ~/.bash_profile' failed" && exit 1
-            echo "# [OK] ... appended ~/.bashrc to ~/.bash_profile"
+            echo "# [OK] ... '~/.bash_profile' appended"
         fi
         unset -v BD_INSTALL_APPEND_BASH_PROFILE
         echo
@@ -132,18 +133,18 @@ if [ "${BD_INSTALL_APPEND}" == "1" ]; then
     if [ -f ~/.bashrc ]; then
         BD_INSTALL_APPEND_BASHRC="$(grep -E -e ' (.|source) (.*)/bd.sh( |$|")' ~/.bashrc) 2> /dev/null"
         if [ ${#BD_INSTALL_APPEND_BASHRC} -gt 0 ]; then
-            echo "# [OK] ... bd.sh is sourced via ~/.bashrc"
+            echo "# [OK] ... '~/.bashrc' sources 'bd.sh'"
         else
             if [ -f ~/.bashrc ]; then
                 cp ~/.bashrc ~/.bashrc.${BD_INSTALL_TIMESTAMP}
                 [ $? -ne 0 ] && echo "# [ERROR] ... 'cp ~/.bashrc ~/.bashrc.${BD_INSTALL_TIMESTAMP}' failed" && exit 1
-                echo "# [OK] ... backed up ~/.bashrc to ~/.bashrc.${BD_INSTALL_TIMESTAMP}"
+                echo "# [OK] ...'~/.bashrc.${BD_INSTALL_TIMESTAMP}' backed up"
                 echo
             fi
             echo >> ~/.bashrc
             echo "source \"${BD_DIR}/bd.sh\" \${@}" >> ~/.bashrc
             [ $? -ne 0 ] && echo "# [ERROR] ... 'echo "source \"${BD_DIR}/bd.sh\" \${@}" >> ~/.bashrc' failed" && exit 1
-            echo "# [OK] ... appended 'echo "source \"${BD_DIR}/bd.sh\" \${@}"' to ~/.bashrc"
+            echo "# [OK] ... '~/.bashrc' appended"
         fi
         unset -v BD_INSTALL_APPEND_BASHRC
         echo
@@ -156,14 +157,14 @@ if [ "${BD_INSTALL_REPLACE}" == "1" ]; then
         if [ -f ~/.bash_profile ]; then
             cp ~/.bash_profile ~/.bash_profile.${BD_INSTALL_TIMESTAMP}
             [ $? -ne 0 ] && echo "# [ERROR] ... 'cp ~/.bash_profile ~/.bash_profile.${BD_INSTALL_TIMESTAMP}' failed" && exit 1
-            echo "# [OK] ... backed up ~/.bash_profile to ~/.bash_profile.${BD_INSTALL_TIMESTAMP}"
+            echo "# [OK] ...'~/.bash_profile.${BD_INSTALL_TIMESTAMP}' backed up"
             echo
         fi
         cp "${BD_DIR}/.bash_profile" ~/.bash_profile
         [ $? -ne 0 ] && echo "'cp ${BD_DIR}/.bash_profile ~/.bash_profile' failed" && exit 1
-        echo "# [OK] ... replaced ~/.bash_profile"
+        echo "# [OK] ... '~/.bash_profile' replaced"
     else
-        echo "# [OK] ... ~/.bash_profile sources ~/.bashrc"
+        echo "# [OK] ... '~/.bash_profile' sources '~/.bashrc'"
     fi
     echo
 
@@ -172,14 +173,14 @@ if [ "${BD_INSTALL_REPLACE}" == "1" ]; then
         if [ -f ~/.bashrc ]; then
             cp ~/.bashrc ~/.bashrc.${BD_INSTALL_TIMESTAMP}
             [ $? -ne 0 ] && echo "# [ERROR] ... 'cp ~/.bashrc ~/.bashrc.${BD_INSTALL_TIMESTAMP}' failed" && exit 1
-            echo "# [OK] ... backed up ~/.bashrc to ~/.bashrc.${BD_INSTALL_TIMESTAMP}"
+            echo "# [OK] ...'~/.bashrc.${BD_INSTALL_TIMESTAMP}' backed up"
             echo
         fi
         cp "${BD_DIR}/.bashrc" ~/.bashrc
         [ $? -ne 0 ] && echo "'cp ${BD_DIR}/.bashrc ~/.bashrc' failed" && exit 1
-        echo "# [OK] ... replaced ~/.bashrc"
+        echo "# [OK] ... '~/.bashrc' replaced"
     else
-        echo "# [OK] ... ~/.bashrc sources bd.sh"
+        echo "# [OK] ... '~/.bashrc' sources 'bd.sh'"
     fi
     echo
 fi
